### ISSUE TITLE
Is it possible to customize calling screen?

### ISSUE THREAD

**Issue by ahmadmuhsink** [Gruveo/sdk-examples-android-java#1]
I am interested in using Gruveo but I really need to customize calling screen for our product to be usable and I didnt see that in current API, isnt it?

another thing we need to look up is possibility to disable chat completely because we already have our own chat system.

**Comment by ahmadmuhsink** [comment]
answered in https://github.com/Gruveo/gruveo-ios-sdk/issues/2

**Comment by artmatsak** [comment]
This has been implemented in the latest release of the Android SDK. Please use the new `Gruveo.GRV_EXTRA_DISABLE_CHAT` parameter in `otherExtas`.
