### ISSUE TITLE
Could not GET 'https://jitpack.io/org/bitbucket/gruveo/gruveo-sdk-android/0.6.5

### ISSUE THREAD

**Issue by xaviraol** [Gruveo/sdk-examples-android-java#14]
Hello, we are experiencing this again (it happened before and was reported in #4 ) :

```
Could not GET 'https://jitpack.io/org/bitbucket/gruveo/gruveo-sdk-android/0.6.5/gruveo-sdk-android-0.6.5.pom'. Received status code 401 from server: Unauthorized
```

We saw that your developers portal was down yesterday for maintenance (for example this one https://about.gruveo.com/integrations/).. Currently those work but we still experience the same... is it related somehow?

**Comment by akkewood** [comment]
Hello. Could you please check it now?
Also we've update our SDK. You can use version 0.7.1 now

**Comment by xaviraol** [comment]
Hello @akkewood , it worked! Thanks a lot!!

Just out of curiosity.. what was happening? The repo became private in jitpack?

**Comment by akkewood** [comment]
Hello @xaviraol. For some reasons repo was unavailable on jitpack, something happens wrong there.

**Comment by xaviraol** [comment]
Hello @akkewood , it's happening again right now.

`https://jitpack.io/org/bitbucket/gruveo/gruveo-sdk-android/0.6.5/gruveo-sdk-android-0.6.5.pom` 

`Received status code 401 from server: Unauthorized`

**Comment by akkewood** [comment]
Hello @xaviraol . Could you check please one more time?
Seems like it works now. Maybe jitpack had some problems today

**Comment by xaviraol** [comment]
Working indeed, thanks !
