### ISSUE TITLE
Gruveo call not working on Android 10

### ISSUE THREAD

**Issue by abdul02123** [Gruveo/sdk-examples-android-java#16]
I have run my app on Android 10 (API Level 29) and when i click the button to start call, app gets crash and receive the following error: 
Unable to start activity ComponentInfo{com.app.myapp/com.gruveo.sdk.ui.CallActivity}: android.view.InflateException: Binary XML file line #17 in com.app.myapp:layout/abc_screen_simple: Binary XML file line #17 in com.app.myapp:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
 
Version:
implementation 'org.bitbucket.gruveo:gruveo-sdk-android:0.6.5'

**Comment by akkewood** [comment]
@abdul02123  Hi, could you please try to use our latest version 0.7.2?

**Comment by abdul02123** [comment]
yes, fixed now - thanks.
