### ISSUE TITLE
could not retrieve gruveo-sdk-android from the repo

### ISSUE THREAD

**Issue by xedixermawan** [Gruveo/sdk-examples-android-java#4]
hi, i got an error when retrieving gruveo sdk : 
```
Could not HEAD 'https://jitpack.io/org/bitbucket/gruveo/gruveo-sdk-android/0.5.11/gruveo-sdk-android-0.5.11.pom'. Received status code 401 from server: Unauthorized
```
it happens as well for other version.
is there any change in sdk link ? @tibbi 
thanks

**Comment by tibbi** [comment]
you shouldnt need any authorization for it. Previous versions are broken too? Do you see those files at https://jitpack.io/#org.bitbucket.gruveo/gruveo-sdk-android ?

**Comment by xedixermawan** [comment]
strangely it just works now ( rebuild it , without change ). I guess there was server problem while ago.
Thanks

**Comment by xaviraol** [comment]
Hello, we are experiencing this again:
```
Could not GET 'https://jitpack.io/org/bitbucket/gruveo/gruveo-sdk-android/0.6.5/gruveo-sdk-android-0.6.5.pom'. Received status code 401 from server: Unauthorized
```

We saw that your developers portal was down yesterday for maintenance (for example this one https://about.gruveo.com/integrations/).. Currently those work but we still experience the same... is it related somehow?
