### ISSUE TITLE
Gruveo Android Integration 

### ISSUE THREAD

**Issue by iOSDevGarg** [Gruveo/sdk-examples-android-java#5]
I have been trying to impelement Gruveo in my Android App. But gruveo call get initiated successfully in some Android devices but in some I am getting following error

**No implementation found for void org.webrtc.PeerConnectionFactory.initializeFieldTrials(java.lang.String) (tried Java_org_webrtc_PeerConnectionFactory_initializeFieldTrials and Java_org_webrtc_PeerConnectionFactory_initializeFieldTrials__Ljava_lang_String_2)**

**Device Used** 

1. Samsung Galaxy J7 Prime 
OS - Android 7.0
Architecture chipset - 64 Bit
Gruveo Status - **Working Fine**

2. Samsung Galaxy S6 
OS - Android 7.0
Architecture chipset - 64 Bit
Gruveo Status -  **Not Working**

My both devices have same chipset but on it works and on other I am getting error as Described above. Please suggest me what I am doing wrong

**Note - I've checked Android Documentation it work fine in both devices and I've used same code in my app. But get above error. Please suggest me possible solution**

**Comment by tibbi** [comment]
Hey, does the official Gruveo app work fine on both devices?

**Comment by iOSDevGarg** [comment]
@tibbi Sir... Yes, Official Gruveo app is working fine on both devices. I have used same code written in Official app code even the same room Name same init Method. but I get that error.  Please help me its urgent

**Comment by iOSDevGarg** [comment]
Issue is Solved it was due to SDk was unable to get Architecture Info 

Check Link - https://android.jlelse.eu/controlling-apk-size-when-using-native-libraries-45c6c0e5b70a

We have to use

    ndk {
            abiFilters "armeabi-v7a", "x86"
        }
