### ISSUE TITLE
Problems to integrate your services with my Android app. Help please

### ISSUE THREAD

**Issue by oelarap** [Gruveo/sdk-examples-android-java#6]
Hello:
I have problems to integrate your services with my Android app.
When i build the app throw me this error:
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.bitbucket.gruveo:gruveo-sdk-android:0.5.11.
Open File
Show Details
Can you please help me searching the error. I attached the gradle:
gradle root:
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:4.0.1'
    }
}
allprojects {
    repositories {
        jcenter()
        google()
        maven { url "https://jitpack.io" }
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
------------------------------------------
Gradle app:
apply plugin: 'com.android.application'
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.cubix.therappy.therappy"
        minSdkVersion 24
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0-rc02'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:design:28.0.0-rc02'
    implementation 'com.android.support:support-v4:28.0.0-rc02'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.code.gson:gson:2.3'
    implementation 'com.google.guava:guava:18.0'
    implementation 'com.squareup.okhttp:okhttp:2.5.0'
    implementation 'com.microsoft.azure:azure-mobile-android:3.2.0@aar'
    implementation 'com.microsoft.azure:azure-notifications-handler:1.0.1@jar'
    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.google.firebase:firebase-messaging:17.0.0'
    implementation 'com.firebase:firebase-jobdispatcher:0.8.5'
    implementation 'org.bitbucket.gruveo:gruveo-sdk-android:0.5.11'
}
apply plugin: 'com.google.gms.google-services'
Thanks!

**Comment by tibbi** [comment]
I guess it was a temporary issue on their side. Can you try adding 0.5.10? Thanks

**Comment by oelarap** [comment]
Still the error, What I can do?

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.bitbucket.gruveo:gruveo-sdk-android:0.5.10.
Open File
Show Details


Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.bitbucket.gruveo:gruveo-sdk-android:0.5.10.
Open File
Show Details


Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve org.bitbucket.gruveo:gruveo-sdk-android:0.5.10.
Open File
Show Details


Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve org.bitbucket.gruveo:gruveo-sdk-android:0.5.10.
Open File
Show Details


Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve org.bitbucket.gruveo:gruveo-sdk-android:0.5.10.
Open File
Show Details

**Comment by tibbi** [comment]
Jitpack modified something related to libraries a bit, but it works fine to me already. Both 0.5.10 and 0.5.11. Just retry it please.

**Comment by oelarap** [comment]
It's working.
Thanks!
