### ISSUE TITLE
DexArchiveBuilderException at runtime. 

### ISSUE THREAD

**Issue by abhaybhusari-dev** [Gruveo/sdk-examples-android-java#7]
**Step to Reproduce:**
**Step 1- **  Create Video calling Android Project using Gruveo SDK
**Step 2- ** Implement Firebase cloud Messaging service (FCM) in it
**Step 3- **  Run the project 

**You will get the following issue. Without using FCM in project gruveo sdk working fine.** 

com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\USER\.gradle\caches\transforms-1\files-1.1\firebase-analytics-impl-11.8.0.aar\79a7eb2ba910e487000beef7e648f0c4\jars\classes.jar |  
-- | --
com.android.builder.dexing.DexArchiveBuilderException: Error while dexing. |  
com.android.tools.r8.CompilationFailedException: Compilation failed to complete |  
com.android.tools.r8.utils.AbortException: Error: Type com.google.android.gms.common.internal.zzf is referenced as an interface from `com.google.android.gms.internal.zzcku`. |  
java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\USER\.gradle\caches\transforms-1\files-1.1\firebase-analytics-impl-11.8.0.aar\79a7eb2ba910e487000beef7e648f0c4\jars\classes.jar |  
com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\USER\.gradle\caches\transforms-1\files-1.1\firebase-analytics-impl-11.8.0.aar\79a7eb2ba910e487000beef7e648f0c4\jars\classes.jar |  
com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\USER\.gradle\caches\transforms-1\files-1.1\firebase-analytics-impl-11.8.0.aar\79a7eb2ba910e487000beef7e648f0c4\jars\classes.jar |  
com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\USER\.gradle\caches\transforms-1\files-1.1\firebase-analytics-impl-11.8.0.aar\79a7eb2ba910e487000beef7e648f0c4\jars\classes.jar |  
com.android.builder.dexing.DexArchiveBuilderException: Error while dexing. |  
com.android.tools.r8.CompilationFailedException: Compilation failed to complete |  
com.android.tools.r8.utils.AbortException: Error: Type com.google.android.gms.common.internal.zzf is referenced as an interface from `com.google.android.gms.internal.zzcku`. |

**Comment by tibbi** [comment]
Just allow multidexing in your project, the issue is not related to the Gruveo SDK. More info at https://developer.android.com/studio/build/multidex

**Comment by abhaybhusari-dev** [comment]
I have already allowed Multiplexing in a project. But not working. If I remove com.google.gms.google-services' then it is working.

**Comment by tibbi** [comment]
well then it is some issue with that library, I cannot say what though. Try googling around.

**Comment by abhaybhusari-dev** [comment]
Right. Its been 3 days I am googling. Did you try Steps to reproduce?

**Comment by tibbi** [comment]
no

**Comment by abhaybhusari-dev** [comment]
Okay,  I think You should try. Then you will understand does gruveo sdk and google play service working together or not?

**Comment by tibbi** [comment]
ye, they should work fine, the problem is somewhere on your side

**Comment by abhaybhusari-dev** [comment]
Okay.

**Comment by artmatsak** [comment]
Just for a quick update, @bhusarisuccess let us know today that the issue was indeed due to some Android Studio misbehavior and that things are now working fine on their end.
